### ISSUE TITLE
[Blueprints, 02-at-scale]: Add Pipeline Policies

### ISSUE THREAD

**Issue by carlosrodlop** [cloudbees-oss/terraform-aws-cloudbees-ci-eks-addon#229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Describe the solution you would like

Adding Pipelines Policies for Timeout, Retry and HA (only for HA controllers)

```
cloudbees-pipeline-policies:
      config:
        policies:
        - name: 'Recommendations for HA'
          action: warning
          rules:
          - haRule
        - name: 'Recommendations for Spot'
          action: warning
          rules:
          - nodeWithoutRetryRule
```
